"""Restaurant menu content displayed on the dining page."""

DINING_MENUS = [
    {
        "id": "food",
        "labels": {
            "pt": {"title": "Carta de Comidas", "intro": "Pequenos-almoços, entradas, pratos principais e massas."},
            "en": {"title": "Food Menu", "intro": "Breakfast, starters, main dishes and pasta."},
        },
        "sections": [
            {"title": {"pt": "Pequeno-almoço", "en": "Breakfast"}, "items": [
                {"name": "Buffet Básico", "price": "750"},
                {"name": "Pequeno-almoço no Prato", "price": "550"},
                {"name": "Omeleta no Prato", "price": "400"},
            ]},
            {"title": {"pt": "Sopa e Entradas", "en": "Soup and Starters"}, "items": [
                {"name": "Sopa do Dia", "price": "260"},
                {"name": "Chamussas (dose de 4)", "price": "200"},
                {"name": "Rissóis (dose de 4)", "price": "220"},
                {"name": "Tosta de Atum", "price": "300"},
                {"name": "Coxinhas", "price": "200"},
            ]},
            {"title": {"pt": "Couvert", "en": "Light Bites"}, "items": [
                {"name": "Camarão ao Alhinho", "price": "400"},
                {"name": "Chouriço Grelhado", "price": "550"},
                {"name": "Moelas Salteadas", "price": "300"},
                {"name": "Prego no Prato", "price": "450"},
                {"name": "Bife Trinchado", "price": "450"},
                {"name": "Lulinhas", "price": "450"},
                {"name": "Club Sandwich", "price": "300"},
            ]},
            {"title": {"pt": "Saladas", "en": "Salads"}, "items": [
                {"name": "Salada de Frango", "price": "350"},
                {"name": "Salada de Atum", "price": "350"},
                {"name": "Salada de Beef", "price": "350"},
                {"name": "Salada de Camarão", "price": "350"},
                {"name": "Salada Tropical", "price": "200"},
                {"name": "Salada Grega", "price": "350"},
            ]},
            {"title": {"pt": "Carnes de Vaca", "en": "Beef"}, "items": [
                {"name": "Beef a Portuguesa", "price": "1 000"},
                {"name": "Picanha Gourmet", "price": "1 100"},
                {"name": "Carne de Vaca Assada na Panela", "price": "700"},
                {"name": "Rabo de Vaca", "price": "700"},
                {"name": "T-Bone", "price": "650"},
            ]},
            {"title": {"pt": "Carnes de Porco", "en": "Pork"}, "items": [
                {"name": "Carne de Porco Estufada", "price": "650"},
                {"name": "Costelas de Porco", "price": "650"},
                {"name": "Entrecosto de Porco", "price": "650"},
            ]},
            {"title": {"pt": "Aves", "en": "Poultry"}, "items": [
                {"name": "Meio Frango com Piri-piri", "price": "500"},
                {"name": "Frango Inteiro com Piri-piri", "price": "900"},
                {"name": "Frango a Zambeziana (meio frango)", "price": "520"},
                {"name": "Pato Estufado", "price": "700"},
            ]},
            {"title": {"pt": "Peixes", "en": "Fish"}, "items": [
                {"name": "Bacalhau a Lagareiro", "price": "1 400"},
                {"name": "Peixe Grelhado Inteiro", "price": "800"},
                {"name": "Peixe Grelhado em Postas", "price": "800"},
            ]},
            {"title": {"pt": "Mariscos", "en": "Seafood"}, "items": [
                {"name": "Bife de Lulas", "price": "1 000"},
                {"name": "Caril de Camarão", "price": "610"},
                {"name": "Camarão Médio Grelhado (8 unidades)", "price": "1 000"},
                {"name": "Camarão Grande Grelhado (4 unidades)", "price": "1 300"},
                {"name": "Matapa com Caranguejo", "price": "610"},
            ]},
            {"title": {"pt": "Massas", "en": "Pasta"}, "items": [
                {"name": "Esparguete a Bolonhesa", "price": "610"},
                {"name": "Massa com Camarão", "price": "610"},
                {"name": "Massa Carbonara", "price": "610"},
            ]},
        ],
    },
    {
        "id": "drinks",
        "labels": {
            "pt": {"title": "Carta de Bebidas", "intro": "Cervejas, destilados, cocktails, sumos e refrescos."},
            "en": {"title": "Drinks Menu", "intro": "Beer, spirits, cocktails, juices and soft drinks."},
        },
        "sections": [
            {"title": {"pt": "Cervejas", "en": "Beer"}, "items": [
                {"name": "Laurentina Preta", "price": "120"}, {"name": "JC Lata", "price": "160"},
                {"name": "2M Garrafa", "price": "100"}, {"name": "2M Lata", "price": "130"},
                {"name": "Castle Lite", "price": "130"}, {"name": "Heineken", "price": "180"},
                {"name": "Txilar (lata)", "price": "100"}, {"name": "Hunter's Gold", "price": "150"},
                {"name": "Corona", "price": "150"}, {"name": "Savana", "price": "130"},
                {"name": "Brutal", "price": "160"},
            ]},
            {"title": {"pt": "Licores", "en": "Liqueurs"}, "items": [
                {"name": "After Shock", "price": "140"}, {"name": "Drambuie", "price": "150"},
                {"name": "Martini Branco", "price": "110"}, {"name": "Martini Tinto", "price": "110"},
                {"name": "Sambuca Gold", "price": "130"}, {"name": "Sambuca Black", "price": "130"},
                {"name": "Sambuca Inferno", "price": "120"}, {"name": "Zappa", "price": "120"},
            ]},
            {"title": {"pt": "Gin", "en": "Gin"}, "subtitle": {"pt": "Garrafa / dose", "en": "Bottle / serve"}, "items": [
                {"name": "Gordon's", "price": "1 800 / 100"}, {"name": "Sapphire", "price": "3 000 / 180"},
                {"name": "Tanqueray", "price": "170"},
            ]},
            {"title": {"pt": "Brandy e Tequila", "en": "Brandy and Tequila"}, "items": [
                {"name": "Brandy", "price": "190"}, {"name": "Richeleu", "price": "120"},
                {"name": "Olmeca Gold", "price": "100"}, {"name": "Olmeca Branco", "price": "130"},
                {"name": "Olmeca Chocolate", "price": "130"},
            ]},
            {"title": {"pt": "Whiskies Velhos", "en": "Aged Whiskies"}, "subtitle": {"pt": "Garrafa / dose", "en": "Bottle / serve"}, "items": [
                {"name": "Chivas 12 Anos", "price": "4 400 / 250"}, {"name": "Dimple", "price": "6 300 / 280"},
                {"name": "Gentleman Jack", "price": "3 800 / 250"}, {"name": "Glenfiddich 12 Anos", "price": "5 000 / 250"},
                {"name": "Glenfiddich 15 Anos", "price": "6 800 / 260"}, {"name": "J. Daniels Single Barrel", "price": "5 800 / 260"},
                {"name": "Johnnie Walker Black Label", "price": "3 900 / 230"}, {"name": "Johnnie Walker Blue Label", "price": "25 000 / 900"},
                {"name": "Johnnie Walker Double Black", "price": "6 300 / 310"}, {"name": "Johnnie Walker Gold Label", "price": "6 300 / 330"},
                {"name": "Johnnie Walker Platinum", "price": "10 500 / 420"}, {"name": "Johnnie Walker Green Label", "price": "7 200 / 320"},
            ]},
            {"title": {"pt": "Whiskies", "en": "Whiskies"}, "subtitle": {"pt": "Garrafa / dose", "en": "Bottle / serve"}, "items": [
                {"name": "Ballantine's", "price": "1 700 / 130"}, {"name": "Black Bottle", "price": "7 000 / 350"},
                {"name": "Famous Grouse", "price": "1 800 / 110"}, {"name": "Grant's", "price": "1 700 / 110"},
                {"name": "J&B", "price": "2 300 / 110"}, {"name": "Jack Daniel's Tennessee", "price": "2 500 / 140"},
                {"name": "Johnnie Walker Red Label", "price": "2 070 / 110"}, {"name": "Jameson Irish", "price": "2 300 / 110"},
                {"name": "Jameson Reserva", "price": "6 000 / 260"},
            ]},
            {"title": {"pt": "Vodka", "en": "Vodka"}, "subtitle": {"pt": "Garrafa / dose", "en": "Bottle / serve"}, "items": [
                {"name": "Absolut", "price": "2 300 / 150"}, {"name": "Belvedere Black", "price": "6 200 / 150"},
                {"name": "Belvedere Citrus", "price": "6 200 / 150"}, {"name": "Belvedere Intense", "price": "6 200 / 150"},
                {"name": "Belvedere Red", "price": "6 200 / 140"}, {"name": "Ciroc", "price": "6 200 / 220"},
                {"name": "Grey Goose", "price": "120"}, {"name": "Sky Vodka", "price": "140"},
                {"name": "Smirnoff", "price": "1 000 / 110"},
            ]},
            {"title": {"pt": "Cocktails", "en": "Cocktails"}, "items": [
                {"name": "Alexander", "price": "350"}, {"name": "Americano", "price": "250"}, {"name": "B-52", "price": "300"},
                {"name": "Black Russian", "price": "300"}, {"name": "Caipirinha", "price": "350"}, {"name": "Caipirinha de Maracujá", "price": "350"},
                {"name": "Caipiroska", "price": "300"}, {"name": "Cosmopolitan", "price": "350"}, {"name": "Dirty Martini", "price": "320"},
                {"name": "Daiquiri", "price": "300"}, {"name": "Margarita", "price": "300"}, {"name": "Mistura de Momento", "price": "280"},
                {"name": "Sex on the Beach", "price": "300"}, {"name": "Turange Passion Fruit (sem álcool)", "price": "210"},
                {"name": "Whiskey Sour", "price": "390"}, {"name": "White Lady", "price": "300"},
                {"name": "Pina Colada", "price": "300"}, {"name": "Pink Lady", "price": "300"},
            ]},
            {"title": {"pt": "Rum, Aguardente e Cognac", "en": "Rum, Brandy and Cognac"}, "subtitle": {"pt": "Garrafa / dose quando aplicável", "en": "Bottle / serve where applicable"}, "items": [
                {"name": "Captain Morgan Black Label", "price": "1 970 / 110"}, {"name": "Captain Morgan Spiced Gold", "price": "2 100 / 110"},
                {"name": "Havana Club", "price": "1 950 / 110"}, {"name": "São Domingos", "price": "140"},
                {"name": "Hennessy", "price": "320"}, {"name": "Remy Martin VSOP", "price": "7 000 / 300"},
            ]},
            {"title": {"pt": "Água, Sumos e Refrescos", "en": "Water, Juices and Soft Drinks"}, "items": [
                {"name": "Água Grande", "price": "130"}, {"name": "Água Pequena", "price": "60"}, {"name": "Água das Pedras", "price": "150"},
                {"name": "Ceres", "price": "250"}, {"name": "Compal", "price": "250"}, {"name": "Sumo Natural", "price": "260"},
                {"name": "Sumo Massala Tropicalisa", "price": "230"}, {"name": "Água Tónica", "price": "100"},
                {"name": "Red Bull", "price": "180"}, {"name": "Soda Water", "price": "100"},
                {"name": "Coca-Cola", "price": "100"}, {"name": "Coca-Cola Zero", "price": "100"},
                {"name": "Sprite Zero", "price": "100"}, {"name": "Dry Lemon", "price": "100"},
                {"name": "Lemonade", "price": "100"}, {"name": "Ginger Ale", "price": "100"},
            ]},
        ],
    },
    {
        "id": "wines",
        "labels": {
            "pt": {"title": "Carta de Vinhos", "intro": "Vinhos tintos, brancos, rose, espumantes e porto."},
            "en": {"title": "Wine List", "intro": "Red, white and rose wines, sparkling wines and port."},
        },
        "sections": [
            {"title": {"pt": "Vinhos Tintos", "en": "Red Wines"}, "items": [
                {"name": "Alandra", "price": "1 050"}, {"name": "Borba Reserva", "price": "2 200"},
                {"name": "Cadeao Reserva", "price": "2 000"}, {"name": "Casa de Insua Reserva", "price": "4 500"},
                {"name": "Casa de Insua Novo", "price": "2 420"}, {"name": "Mar del Sur", "price": "1 200"},
                {"name": "EA Reserva", "price": "3 800"}, {"name": "EA Novo", "price": "1 700"},
                {"name": "Cellar Cask", "price": "1 050"}, {"name": "Monte Velho", "price": "2 050"},
                {"name": "Esporao Reserva", "price": "3 750"}, {"name": "Portada", "price": "1 350"},
                {"name": "Silk Space", "price": "2 500"}, {"name": "Reguengos Garrafeira dos Socios", "price": "2 420"},
                {"name": "Trio Reserva", "price": "2 200"}, {"name": "Trivento", "price": "1 700"},
                {"name": "Segredos de Sao Miguel Normal", "price": "1 600"}, {"name": "Segredos de Sao Miguel Reserva", "price": "2 990"},
                {"name": "Segredos de Sao Miguel Select", "price": "3 900"}, {"name": "Frontera", "price": "1 050"},
                {"name": "Fat Bastard", "price": "1 300"}, {"name": "Cabriz Tinto", "price": "1 175"},
                {"name": "Astica Cabernet Sauvignon", "price": "900"}, {"name": "Instinto Supremo Reserva", "price": "3 200"},
                {"name": "Instinto Normal", "price": "2 800"},
            ]},
            {"title": {"pt": "Vinhos Brancos e Rose", "en": "White and Rose Wines"}, "items": [
                {"name": "Fleur du Cap Chardonnay", "price": "1 610"}, {"name": "Astica Chardonnay", "price": "900"},
                {"name": "Aveleda", "price": "1 820"}, {"name": "Nederburg Sauvignon Blanc", "price": "1 100"},
                {"name": "Nederburg Lyric", "price": "1 150"}, {"name": "Springfield Estate Chardonnay", "price": "1 150"},
                {"name": "Fat Bastard", "price": "1 300"}, {"name": "Spier", "price": "1 300"},
                {"name": "Thelema Chardonnay", "price": "1 700"}, {"name": "Whole Berry Cabernet Sauvignon", "price": "1 550"},
                {"name": "Wild Beast Chardonnay", "price": "870"}, {"name": "Monte Velho Branco", "price": "1 300"},
                {"name": "Cabriz Branco", "price": "1 400"}, {"name": "Casal Garcia", "price": "1 260"},
                {"name": "Esporao Reserva", "price": "4 000"}, {"name": "Gatao 750 ml", "price": "750"},
                {"name": "Mateus Rose", "price": "520"}, {"name": "Gatao Verde 1 L", "price": "1 030"},
                {"name": "Robertson Winery 1.5 L", "price": "1 080"}, {"name": "Robertson Winery 750 ml", "price": "900"},
            ]},
            {"title": {"pt": "Espumantes e Porto", "en": "Sparkling Wines and Port"}, "items": [
                {"name": "Porto Ferreira", "price": "170"}, {"name": "Cavantina Prosecco", "price": "2 230"},
                {"name": "Cavantina Moscato Dolce", "price": "2 230"}, {"name": "Tosti Moscato Brut Gold", "price": "2 842"},
                {"name": "JC Leroux", "price": "1 100"}, {"name": "Moet Chandon Nectar", "price": "8 740"},
                {"name": "Moet Chandon Brut", "price": "7 360"}, {"name": "Tosti Moscato", "price": "1 600"},
                {"name": "Lambrusco", "price": "1 750"}, {"name": "Tosti Pink", "price": "2 100"},
            ]},
        ],
    },
]
